### ISSUE TITLE
The links doesn't work

### ISSUE THREAD

**Issue by Sadat97** [MostafAanwar/WeCare#1]
I tried pressing on the links but it doesn't work

**Comment by MostafAanwar** [comment]
> I tried pressing on the links but it doesn't work

If you mean the links of the page yes I am aware of that, other than that if you mean the deploy links they are working fine.

**Comment by MostafAanwar** [comment]
If you are facing any more issues please let me know.

**Comment by Sadat97** [comment]
Just the links inside the page, thanks for replying so fast
